### ISSUE TITLE
Possible problems with crossovers

### ISSUE THREAD

**Issue by soylomass** [ashayp22/AshayNEAT#3]
I've been trying the library, and I've noticed that even though links and neurons are added to genomes through mutations, new neurons and links are never passed to offspring through crossover.

So after any amount of generations, the genomes have just as many neurons and links as the first generation.

What could be happening?

PS: I'm using the Java library.

> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 9 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum **9** dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 9 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum **9** dad 8 baby 8
> 02:44:35 - mum 8 dad **9** baby 8
> 02:44:35 - mum **9** dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8
> 02:44:35 - mum 8 dad 8 baby 8

**Comment by ashayp22** [comment]
I'm quite busy with school right now. I will take a look at this in the next few weeks and give you a thorough response.

**Comment by soylomass** [comment]
Thanks!

**Comment by ashayp22** [comment]
@soylomass I now have some time to look at this issue. I have a couple of questions for you:

- What are you using this for? A game or some other task?
- How many inputs and outputs do your neural networks have?
- By what generation is this issue showing?
- Have you tried visualizing the neural networks, and if so, do they look the same after many generations?

**Comment by soylomass** [comment]
1. I was trying to make an AI for deeeep.io, think of it as 2d fish in an aquarium, they have to eat nearby food and escape from nearby predators.
2. I tried a few variations, but the most simple is:

Inputs:
- 1 if there's nearby food, 0 if there isn't
- Angle from fish to nearby food in radians, or 0 if there's no food
- 1 if there's a nearby predator, 0 if there isn't
- Angle from fish to predator in radians, or 0 if there's no predator
- I also added a bias input with a value of 1, don't know if it's needed.

Output:
- Angle towards which the fish should move to (the output is 0 to 1, I lerp it from -PI to +PI)

3. The issue is visible in random generations. The amount of genes of the baby is always the smallest number between the mum and the dad, so it only increases when both the mum and dad increased their genes through mutation:

> 12:56:42 - mum 9 dad 9 baby 9
> 12:56:42 - mum 8 dad 10 baby 8
> 12:56:42 - mum 8 dad 9 baby 8
> 12:56:42 - mum 9 dad 8 baby 8
> 12:56:42 - mum 8 dad 9 baby 8
> 12:56:42 - mum 10 dad 9 baby 9
> 12:56:42 - mum 9 dad 9 baby 9
> 12:56:42 - mum 9 dad 9 baby 9
> 12:56:42 - mum 8 dad 8 baby 8
> 12:56:42 - mum 8 dad 8 baby 8

4. No. Do you have any tool I can use to visualize them?

**Comment by ashayp22** [comment]
I do not have any tools for visualizing. However, I do provide access to the x and y positions of each node and link for a specific neural network. All you have to do is find some Java library that can create some circles and lines. Here is some code that I created for a game engine called jMonkeyEngine. It visualizes the neural network in 3D space instead of 2D space:

            float zPos = player.geometry.getLocalTranslation().z + 5; //side to side
            float xOffset = cam.getLocation().x - 10;
            float yOffset = cam.getLocation().y;
        
            for (int i = 0; i < bestNN.getNNsize(); i++) //for each of the nodes
            {
                Vector2 pos = bestNN.getNodePosition(i); //gets the position of the node

                //create the graphic
                Sphere s = new Sphere(30, 30, 1);
                Box b = new Box(Vector3f.ZERO, 1, 1, 1);
                Geometry geom = new Geometry("Box", s);
                Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
                mat.setColor("Color", ColorRGBA.Red);
                geom.setMaterial(mat);
           
                geom.setLocalTranslation(-pos.getX() + xOffset, pos.getY() + yOffset, zPos); //sets the location
           
                //adds to the arraylist and the rootnode(screen)
                rootNode.attachChild(geom);
                nodeList.add(geom);

                //create its connections

                ArrayList<PLink> connectionList = bestNN.getNeuronFromIndex(i).getVecLinksOut(); //gets every link

                for(PLink link : connectionList) //creates the lines
                {
                    //gets the start and end position 
                    Vector2 startPos = pos;
                    Vector2 endPos = bestNN.getNodePositionFromID(link.getPOut().getNeuronId()); //neuron connecting to the current neuron
               
                    //create a line
                    Line line = new Line(new Vector3f(-startPos.getX() + xOffset, startPos.getY() + yOffset, zPos), new Vector3f(-endPos.getX() + xOffset, endPos.getY() + yOffset, zPos));
                
                    //the weight
                    float weight = (float)Math.abs(link.getWeight()) * 5;

                    if(weight < 1) {
                        weight = 1;
                    }
                
                
                    line.setLineWidth(weight);
                
                    //graphic
                    
                    Geometry geometry = new Geometry("Bullet", line);
                    Material mat2 = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
                
                    
                    //sets color to differentiate positive vs negative
                    if(link.getWeight() < 0) {
                        mat2.setColor("Color", ColorRGBA.Red); //red is negative
                    } else {
                        mat2.setColor("Color", ColorRGBA.Blue); //blue is positive
                    }
                
                    //adds tp screen
                    geometry.setMaterial(mat2);                  
                    rootNode.attachChild(geometry);
                    lineList.add(geometry);
                }
                
            }

**Comment by ashayp22** [comment]
@soylomass Try seeing if you can add some code that can visualize the neural networks for a specific member of the population. Above, the bestNN that I use is the NeuralNet of the best member in the population. 

When performing crossover, I made it such that if the parent, either the mom or dad, isn't the fitter parent, then their excess genes will be left out. This may be reason for why the amount of genes of the baby is always the smallest number between the mum and the dad. 

Try increasing the mutation rate and decreasing the chance to add a link so the algorithm changes the weights more. This is found in Settings.java. From past projects, my version of NEAT hasn't done a good job at figuring out optimal angles. Can you make sure all of your inputs are between 0 and 1? You also don't need a bias. That is already a part of every neural network.

**Comment by soylomass** [comment]
Hi, first of all, I'll try to setup the visualizer as soon as possible and report to you when I do.

> my version of NEAT hasn't done a good job at figuring out optimal angles. 

Why? Is there anything that can be done to improve that?

> Can you make sure all of your inputs are between 0 and 1?

Oh, I didn't know they should be between 0 and 1, I was sending the angles in Radians. I'll change that.

Sorry, I'm new to neural networks so I don't really know how things should be done.

**Comment by ashayp22** [comment]
I've always made my inputs between 0 and 1. -1 and 1 will also work, but I've never tried. Feel free to experiment with this.

Regarding the angles, as long as you pass in enough information that will help the algorithm decide to turn left or right, then it doesn't matter. I think the two angle inputs that you have are good. 

Please let me know if you can visualize the network. Also, please try increasing the mutation rate. The problem may be that the link weights are off, and adding more links between the neurons won't help.
